name: Main CI-pipeline

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Checkstyle
        run: dotnet format --verify-no-changes

      - name: Restore dependencies
        run: dotnet restore

      - name: Install Required Tools
        run: |
          dotnet new tool-manifest
          dotnet tool install dotnet-coverage
          dotnet tool install coverlet.console

      - name: Build
        run: dotnet build --no-restore /p:ContinuousIntegrationBuild=true

      - name: Coverage and test
        run: dotnet coverlet StarshipGame.Tests/bin/Debug/net8.0/StarshipGame.Tests.dll --target "dotnet" --targetargs "test --no-build /p:CollectCoverage=true" -f opencover -o "coverage.xml"
