name: CI for Checkstyle and Test Coverage

on:
  pull_request:

permissions:
  pull-requests: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Checkstyle
        run: dotnet format --verify-no-changes

      - name: Restore dependencies
        run: dotnet restore StarshipGame.sln

      - name: Build Project
        run: dotnet build StarshipGame.sln --configuration Release

      - name: Run Tests with Code Coverage
        run: |
          dotnet test StarshipGame.Tests/StarshipGame.Tests.csproj \
            --configuration Release \
            --no-build \
            --collect:"XPlat Code Coverage" \
            --logger trx \
            --results-directory coverage

      - name: Install ReportGenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: Generate Coverage Report
        run: |
          reportgenerator \
            "-reports:coverage/*/coverage.cobertura.xml" \
            "-targetdir:coveragereport" \
            "-reporttypes:TextSummary;Cobertura"

      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: 'coverage/*/coverage.cobertura.xml'
          badge: true
          format: 'markdown'
          output: 'both'
          indicators: true

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md

      - name: Show Coverage Details
        run: |
          echo "## 📈 Code Coverage Report" >> $GITHUB_STEP_SUMMARY
          echo "### 📊 Coverage Summary" >> $GITHUB_STEP_SUMMARY
          cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
